"""Generate the deployable pages from the design-canvas sources.

The .dc.html files are what the canvas tool reads and writes, and their names
carry spaces, so they can't be served as clean URLs. This copies each one to
its published name and rewrites the links between them. Nothing else moves:
every asset path in those files is already relative to this directory, which
is also what GitHub Pages serves as the site root.

Run after any edit to a .dc.html file:  py build.py
"""

import io
import os

HERE = os.path.dirname(os.path.abspath(__file__))

# source .dc.html -> published name
PAGES = {
    "Landing Hero Background.dc.html": "index.html",
    "Menu.dc.html": "menu.html",
}

BANNER = "<!-- Generated by build.py from {src} - do not edit; edit the source. -->\n"


def main():
    for src, out in PAGES.items():
        path = os.path.join(HERE, src)
        with io.open(path, encoding="utf-8") as fh:
            html = fh.read()

        # Rewrite every cross-page link to its published counterpart. Done for
        # all pages, not just the other one, so adding a third page needs only
        # a PAGES entry.
        for other_src, other_out in PAGES.items():
            html = html.replace('href="%s"' % other_src, 'href="%s"' % other_out)

        html = BANNER.format(src=src) + html

        with io.open(os.path.join(HERE, out), "w", encoding="utf-8", newline="\n") as fh:
            fh.write(html)
        print("%s -> %s" % (src, out))


if __name__ == "__main__":
    main()
