"""Generate the deployable pages from the design-canvas sources.

The .dc.html files are what the canvas tool reads and writes, and their names
carry spaces, so they can't be served as clean URLs. This copies each one to
its published name and rewrites the links between them. Nothing else moves:
every asset path in those files is already relative to this directory, which
is also what GitHub Pages serves as the site root.

Run after any edit to a .dc.html file:  py build.py

Pass --keep-image-slot to publish both pages with <image-slot> intact, which is
what the phone photo-tryout loop needs. See publish_photos().
"""

import io
import os
import re
import sys

import menu_render

HERE = os.path.dirname(os.path.abspath(__file__))

# Pages whose content comes from menu.json rather than from the .dc.html body.
# The .dc.html still owns how a tile looks; menu.json owns what it says.
RENDERED = {"Menu.dc.html": menu_render.apply}

# source .dc.html -> published name
PAGES = {
    "Landing Hero Background.dc.html": "index.html",
    "Menu.dc.html": "menu.html",
}

BANNER = "<!-- Generated by build.py from {src} - do not edit; edit the source. -->\n"

# Pages published without the design-canvas runtime. See flatten().
STATIC = set(PAGES)

# Pages whose <image-slot> authoring controls become plain <img> on the way
# out, and the function that does it. Both pages are here now: the landing's
# single photo turned out to pay the same costs as the menu's eighty-nine and
# two more besides — it is the only image on either page whose frame changes
# SHAPE between phone and desktop, and it is the only one that carries meaning
# a screen reader has no other way to reach. See publish_landing_photo().
PHOTOS = {}

HELMET_RE = re.compile(r"[ \t]*<helmet\b[^>]*>\n?(.*?)[ \t]*</helmet>\n?", re.S | re.I)
XDC_RE = re.compile(r"[ \t]*</?x-dc\b[^>]*>\n?", re.I)
SCRIPT_RE = re.compile(r"[ \t]*<script\b(?:(?!</script>).)*?</script>\n?", re.S | re.I)
SCRIPT_SRC_RE = re.compile(r"<script(\s+src=)", re.I)


def flatten(html, src):
    """Publish a page that paints from its own HTML and CSS, with no runtime.

    The canvas runtime hides the entire template behind `x-dc{display:none}`
    until React has arrived, compiled the markup and mounted its own copy of
    it. Measured on this machine that is ~0.9s before the page is even the
    right colour and ~3s before a word of it is on screen, and every one of
    those bytes is spent rebuilding markup that is already complete in the
    file. Nothing here needs it: the menu carries no bindings at all, and the
    landing's two are driven from scroll by a plain script.

    The cost was invisible while the pages were only ever loaded cold. It stops
    being invisible the moment they transition into each other - a cross-document
    view transition snapshots the incoming page at its first paint, which under
    the runtime is a blank rectangle.

    The .dc.html files are untouched by this; the canvas tool still opens them
    and still renders them through the runtime. This only changes what ships.
    """
    head, sep, body = html.partition("</head>")
    if not sep:
        raise SystemExit("%s: no </head>" % src)

    # The runtime's loader, and the hook that repoints its CDN at assets/vendor.
    def drop_runtime(match):
        block = match.group(0)
        runtime = "window.__resources" in block or "support.js" in block
        return "" if runtime else block

    head = SCRIPT_RE.sub(drop_runtime, head)
    if "support.js" in head:
        raise SystemExit("%s: runtime loader survived the strip" % src)

    # <helmet> is the runtime's own "put this in <head>" envelope. Without it
    # to do the moving, the build does it - at which point the stylesheet is a
    # normal blocking stylesheet in <head> and the page paints styled.
    helmets = HELMET_RE.findall(body)
    if len(helmets) != 1:
        raise SystemExit("%s: expected 1 <helmet>, found %d" % (src, len(helmets)))
    hoisted = HELMET_RE.sub("", body, count=1)

    # Scripts ride along deferred. They define custom elements used further
    # down the page and none of them writes during parse, so blocking the
    # first paint on them would give back the delay this whole function exists
    # to remove.
    head_add = SCRIPT_SRC_RE.sub(r"<script defer\1", helmets[0])

    body = XDC_RE.sub("", hoisted)
    if "<x-dc" in body:
        raise SystemExit("%s: x-dc wrapper survived the strip" % src)

    return head + head_add + sep + body


# --- photos -----------------------------------------------------------------

SLOT_RE = re.compile(r"<image-slot\b([^>]*?)>\s*</image-slot>", re.I)
ATTR_RE = re.compile(r'([\w:-]+)\s*=\s*"([^"]*)"')

# Matched on the src, not on the bare filename: the page's own comments talk
# about these files, and a looser pattern would delete an inline script for
# mentioning one.
PHOTO_SCRIPT_RE = re.compile(
    r'[ \t]*<script\b[^>]*\bsrc\s*=\s*"[^"]*(?:image-slot|photo-tryout)\.js"[^>]*>'
    r"\s*</script>\n?",
    re.I,
)

# Measured, not guessed: the tile is 141 CSS px on a 375px phone and a fixed
# 285 px once the 720px column stops growing, which happens around 880.
SIZES = "(min-width: 880px) 285px, 38vw"

# The first rows are on screen before a finger moves, so they are not lazy —
# lazy above the fold just delays the only photos anyone is guaranteed to see.
EAGER = 4
PRIORITY = 2

FORCE_MENU_IMAGE_PREVIEW = True
FORCE_MENU_IMAGE_SRC = "assets/menu/opt/rf-02.webp"


def publish_photos(html, src):
    """Publish the menu's photos as plain <img>, not as a custom element.

    <image-slot> is the design-canvas tool's authoring control: it takes a
    dropped file, downscales it through a canvas and remembers it in a sidecar.
    That is the right thing in the tool and the wrong thing on a phone at a
    table — it is 65KB of JavaScript standing between the reader and every
    photo on the page, to end up drawing the <img> the browser would have drawn
    on its own. Worse, nothing paints until it has parsed: measured, the page
    holds 89 pulsing rectangles until that file lands.

    So the source keeps <image-slot> and the canvas tool keeps working; this
    rewrites it on the way out. Same trade flatten() already makes one function
    up, for the same reason.

    What the element cannot express and a plain <img> can: a second width for
    phones, native lazy loading, an intrinsic size so the tile never shifts,
    and an alt attribute that is ours to set rather than hard-coded empty in a
    vendor file.
    """
    seen = [0]

    def convert(match):
        attrs = dict(ATTR_RE.findall(match.group(1)))
        photo = (
            FORCE_MENU_IMAGE_SRC
            if FORCE_MENU_IMAGE_PREVIEW
            else attrs.get("data-src") or attrs.get("src") or ""
        )

        # No photo for this item yet. menu_render points those at a shared
        # placeholder file so the canvas tool has something to show while
        # authoring, but shipping one identical stand-in twenty-six times tells
        # the reader the site is unfinished. An empty tile is the honest state,
        # and it costs no request at all.
        if not photo or photo.endswith(menu_render.PLACEHOLDER):
            return '<span class="item-photo-empty" aria-hidden="true"></span>'

        i = seen[0]
        seen[0] += 1
        stem, _, ext = photo.rpartition(".")
        small = "%s-300.%s" % (stem, ext)

        bits = [
            'src="%s"' % photo,
            'srcset="%s 300w, %s 600w"' % (small, photo),
            'sizes="%s"' % SIZES,
            'width="600"',
            'height="600"',
            # Deliberately empty. Every one of these sits directly beside an
            # <h3> carrying the item's name and a <p> describing it, so a
            # screen reader that also announced "photo of latte" would read the
            # same item twice. Decorative is the accurate answer here, and now
            # it is an answer this project makes rather than one it inherits.
            'alt=""',
            'decoding="async"',
        ]
        if i < EAGER:
            if i < PRIORITY:
                bits.append('fetchpriority="high"')
        else:
            bits.append('loading="lazy"')
        return "<img %s>" % " ".join(bits)

    html, n = SLOT_RE.subn(convert, html)
    html = strip_slot_machinery(html, src)
    print("  %d photos published as <img>" % n)
    return html


def strip_slot_machinery(html, src):
    """Drop what only existed to drive <image-slot>, once none are left."""
    # Matched on a slot that still carries its persistence id, not on the bare
    # tag name: the page's own comments discuss this element, and a looser check
    # fails the build over prose.
    if re.search(r"<image-slot\b[^>]*\bid=", html):
        raise SystemExit("%s: an image-slot element survived the rewrite" % src)

    # The two scripts that existed only to drive those elements. photo-tryout
    # goes with them: it is an <image-slot> tool, and it already refused to arm
    # anywhere but localhost and github.io, neither of which is the host now.
    html = PHOTO_SCRIPT_RE.sub("", html)
    if PHOTO_SCRIPT_RE.search(html):
        raise SystemExit("%s: a photo script survived the strip" % src)
    return html


# The landing photo is one shape at every width now, so it is one srcset and no
# art direction. The frame used to take its height from the viewport and let
# object-fit resolve the mismatch, which meant a 3:4 crop for the phone and a
# sixth of the height gone on a wide desktop; it now takes the photograph's own
# 1920x1220 and nothing is cut anywhere. <picture> stays as the wrapper because
# the skeleton's CSS selects through it, but it carries a single source.
LANDING_SET = (
    ("assets/cafe-interior-480.webp", 480),
    ("assets/cafe-interior-760.webp", 760),
    ("assets/cafe-interior-1280.webp", 1280),
    ("assets/cafe-interior.webp", 1920),
)
# Full width below 640, where the start-side inset is dropped. Above it the
# frame is the viewport minus that inset, which is 8vw until the clamp caps it
# at 140px (at 1750px).
LANDING_SIZES = (
    "(max-width: 640px) 100vw, (min-width: 1750px) calc(100vw - 140px), 92vw"
)


def publish_landing_photo(html, src):
    """Publish the landing's one photo as a <picture>, not as a custom element.

    Everything publish_photos() says about the menu applies here, and the
    landing adds one the menu never had.

    This frame used to be portrait on a phone and landscape on a desktop, and
    the two shapes needed two crops — which <picture> exists for, and which
    <image-slot> cannot express with its single src. The frame now carries the
    photograph's own ratio instead, so there is one shape, one srcset, and
    nothing cropped at any width. The wrapper stays because the skeleton's CSS
    selects through it.

    ALT TEXT. image-slot.js hard-codes alt="" into its shadow root and does not
    observe an alt attribute, so this photograph could not be given an
    accessible name by any markup in this project — the caption in the source
    is `placeholder`, which is authoring chrome and never reaches the page. The
    menu's photos are honestly decorative: each one sits beside an <h3> naming
    the item. This one is not. It is the only view of the room the page offers,
    it sits under a heading about the room, and nothing else on the page says
    what it shows. So the source carries data-alt and it lands on the <img>.

    Removing the element also takes 64KB of image-slot.js and the
    .image-slots.state.json round trip off a page that has one photograph.
    """
    alt_seen = []

    def convert(match):
        attrs = dict(ATTR_RE.findall(match.group(1)))
        photo = attrs.get("data-src") or attrs.get("src") or ""
        if not photo:
            raise SystemExit("%s: landing slot has no src" % src)

        alt = attrs.get("data-alt")
        if alt is None:
            # Not defaulted to empty on purpose. An unnamed photograph here is
            # a content gap the owner has to fill, and a build that silently
            # shipped alt="" would hide it exactly the way the custom element
            # did. PRODUCT.md's rule: a blank stays visibly blank.
            raise SystemExit(
                "%s: landing slot needs data-alt (or a decision that it is decorative)" % src
            )
        alt_seen.append(alt)

        srcset = ", ".join("%s %dw" % (f, w) for f, w in LANDING_SET)
        return (
            # The srcset rides on the <img>, not on a <source>. With the art
            # direction gone there is one candidate list, and a single-source
            # <picture> wraps it in an element that decides nothing. The
            # wrapper itself stays only because the skeleton's CSS selects
            # through it.
            '<picture>'
            # width/height are the file's real ratio, and now the frame's too —
            # .photo carries aspect-ratio:1920/1220, so these describe the box
            # the browser reserves rather than contradicting it.
            # No loading="lazy". It looks right for something 1.45 viewports
            # down, and it is wrong here: the skeleton above this frame reveals
            # on whichever comes first, the image settling or a timeout, and a
            # deferred image loses that race - measured, the skeleton faded out
            # over an empty frame and the photo arrived after it. An ordinary
            # below-the-fold <img> is already deprioritised by the browser
            # without breaking that contract, which is all the finding asked
            # for; what had to go was the fetchpriority="high" on the preload.
            '<img src="%s" srcset="%s" sizes="%s"'
            ' width="1920" height="1220" alt="%s" decoding="async">'
            "</picture>"
        ) % (
            # The fallback for anything that cannot read a srcset — a mid tier,
            # not the 1920. Nothing modern reaches it.
            LANDING_SET[-2][0],
            srcset,
            LANDING_SIZES,
            alt,
        )

    html, n = SLOT_RE.subn(convert, html)
    if n != 1:
        raise SystemExit("%s: expected 1 landing photo, converted %d" % (src, n))

    # The preload this replaces. It existed because <image-slot> hid the URL
    # from the preload scanner — the comment on it records the photo starting
    # 370ms after an HTML document that was complete at 61ms. A <picture> in
    # the markup is discovered by that same scanner at parse time, with no hint
    # needed and no fetchpriority="high" stealing bandwidth from the two fonts
    # that are actually above the fold.
    # The comment above it goes too, and is matched as part of the same unit so
    # a published page can never be left explaining a hint it does not carry.
    html, dropped = re.subn(
        r"[ \t]*<!--(?:(?!-->).)*?-->\s*"
        r'<link\b[^>]*\brel="preload"[^>]*\bhref="assets/cafe-interior\.webp"[^>]*>\n?',
        "",
        html,
        flags=re.S,
    )
    if dropped != 1:
        raise SystemExit("%s: expected to drop 1 photo preload, dropped %d" % (src, dropped))

    html = strip_slot_machinery(html, src)
    # Character count, not the string: this console is cp1256 and printing
    # Persian to it raises UnicodeEncodeError, which would fail a build that
    # had already succeeded.
    print("  landing photo published as <picture> (alt: %d chars)" % len(alt_seen[0]))
    return html


PHOTOS.update({
    "Menu.dc.html": publish_photos,
    "Landing Hero Background.dc.html": publish_landing_photo,
})


def main():
    keep_slots = "--keep-image-slot" in sys.argv

    for src, out in PAGES.items():
        path = os.path.join(HERE, src)
        with io.open(path, encoding="utf-8") as fh:
            html = fh.read()

        if src in RENDERED:
            html = RENDERED[src](html)

        if src in STATIC:
            html = flatten(html, src)

        if src in PHOTOS and not keep_slots:
            html = PHOTOS[src](html, src)

        # Rewrite every cross-page link to its published counterpart. Done for
        # all pages, not just the other one, so adding a third page needs only
        # a PAGES entry.
        for other_src, other_out in PAGES.items():
            html = html.replace('href="%s"' % other_src, 'href="%s"' % other_out)

        html = BANNER.format(src=src) + html

        with io.open(os.path.join(HERE, out), "w", encoding="utf-8", newline="\n") as fh:
            fh.write(html)
        print("%s -> %s" % (src, out))


if __name__ == "__main__":
    main()
