"""Generate the deployable pages from the design-canvas sources.

The .dc.html files are what the canvas tool reads and writes, and their names
carry spaces, so they can't be served as clean URLs. This copies each one to
its published name and rewrites the links between them. Nothing else moves:
every asset path in those files is already relative to this directory, which
is also what GitHub Pages serves as the site root.

Run after any edit to a .dc.html file:  py build.py
"""

import io
import os
import re

import menu_render

HERE = os.path.dirname(os.path.abspath(__file__))

# Pages whose content comes from menu.json rather than from the .dc.html body.
# The .dc.html still owns how a tile looks; menu.json owns what it says.
RENDERED = {"Menu.dc.html": menu_render.apply}

# source .dc.html -> published name
PAGES = {
    "Landing Hero Background.dc.html": "index.html",
    "Menu.dc.html": "menu.html",
}

BANNER = "<!-- Generated by build.py from {src} - do not edit; edit the source. -->\n"

# Pages published without the design-canvas runtime. See flatten().
STATIC = set(PAGES)

HELMET_RE = re.compile(r"[ \t]*<helmet\b[^>]*>\n?(.*?)[ \t]*</helmet>\n?", re.S | re.I)
XDC_RE = re.compile(r"[ \t]*</?x-dc\b[^>]*>\n?", re.I)
SCRIPT_RE = re.compile(r"[ \t]*<script\b(?:(?!</script>).)*?</script>\n?", re.S | re.I)
SCRIPT_SRC_RE = re.compile(r"<script(\s+src=)", re.I)


def flatten(html, src):
    """Publish a page that paints from its own HTML and CSS, with no runtime.

    The canvas runtime hides the entire template behind `x-dc{display:none}`
    until React has arrived, compiled the markup and mounted its own copy of
    it. Measured on this machine that is ~0.9s before the page is even the
    right colour and ~3s before a word of it is on screen, and every one of
    those bytes is spent rebuilding markup that is already complete in the
    file. Nothing here needs it: the menu carries no bindings at all, and the
    landing's two are driven from scroll by a plain script.

    The cost was invisible while the pages were only ever loaded cold. It stops
    being invisible the moment they transition into each other - a cross-document
    view transition snapshots the incoming page at its first paint, which under
    the runtime is a blank rectangle.

    The .dc.html files are untouched by this; the canvas tool still opens them
    and still renders them through the runtime. This only changes what ships.
    """
    head, sep, body = html.partition("</head>")
    if not sep:
        raise SystemExit("%s: no </head>" % src)

    # The runtime's loader, and the hook that repoints its CDN at assets/vendor.
    def drop_runtime(match):
        block = match.group(0)
        runtime = "window.__resources" in block or "support.js" in block
        return "" if runtime else block

    head = SCRIPT_RE.sub(drop_runtime, head)
    if "support.js" in head:
        raise SystemExit("%s: runtime loader survived the strip" % src)

    # <helmet> is the runtime's own "put this in <head>" envelope. Without it
    # to do the moving, the build does it - at which point the stylesheet is a
    # normal blocking stylesheet in <head> and the page paints styled.
    helmets = HELMET_RE.findall(body)
    if len(helmets) != 1:
        raise SystemExit("%s: expected 1 <helmet>, found %d" % (src, len(helmets)))
    hoisted = HELMET_RE.sub("", body, count=1)

    # Scripts ride along deferred. They define custom elements used further
    # down the page and none of them writes during parse, so blocking the
    # first paint on them would give back the delay this whole function exists
    # to remove.
    head_add = SCRIPT_SRC_RE.sub(r"<script defer\1", helmets[0])

    body = XDC_RE.sub("", hoisted)
    if "<x-dc" in body:
        raise SystemExit("%s: x-dc wrapper survived the strip" % src)

    return head + head_add + sep + body


def main():
    for src, out in PAGES.items():
        path = os.path.join(HERE, src)
        with io.open(path, encoding="utf-8") as fh:
            html = fh.read()

        if src in RENDERED:
            html = RENDERED[src](html)

        if src in STATIC:
            html = flatten(html, src)

        # Rewrite every cross-page link to its published counterpart. Done for
        # all pages, not just the other one, so adding a third page needs only
        # a PAGES entry.
        for other_src, other_out in PAGES.items():
            html = html.replace('href="%s"' % other_src, 'href="%s"' % other_out)

        html = BANNER.format(src=src) + html

        with io.open(os.path.join(HERE, out), "w", encoding="utf-8", newline="\n") as fh:
            fh.write(html)
        print("%s -> %s" % (src, out))


if __name__ == "__main__":
    main()
